name: Calendis Scraper

on:
  schedule:
    - cron: "0 * * * *"  # Adjust the cron schedule as needed
  workflow_dispatch:  # Allows manual runs

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: Production  # Use the Production environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Run scraper
        env:
          SCRAPING_ENABLED: ${{ vars.SCRAPING_ENABLED }}
          SERVICE_ID: ${{ vars.SERVICE_ID }}
          CHECK_DAYS_AHEAD: ${{ vars.CHECK_DAYS_AHEAD }}
          CHECK_SPECIFIC_DAYS: ${{ vars.CHECK_SPECIFIC_DAYS }}
          TIME_INTERVAL_START: ${{ vars.TIME_INTERVAL_START }}
          TIME_INTERVAL_END: ${{ vars.TIME_INTERVAL_END }}
          CLIENT_SESSION: ${{ vars.CLIENT_SESSION }}
          TELEGRAM_TOKEN: ${{ vars.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ vars.TELEGRAM_CHAT_ID }}
        run: python scraper.py
